name: 'Send Task to Tasker'
description: 'Submits a new task to tasker'
inputs:
  source:
    description: 'The source id of the repository'
    required: true
  command:
    description: 'The command to call in the source'
    required: true
  token:
    description: 'The token to use to access the Tasker API'
    required: true
  envJSON:
    description: 'Environment variables your task needs to access'
    required: false
    default: '{}'
runs:
  using: 'node16'
  main: 'index.js'